name: 'Ghost Scanner Security Scan'
description: 'AI-enhanced CI/CD security scanning for secrets and dependencies'
author: 'Ghost Scanner Team'

inputs:
  api_url:
    description: 'Ghost Scanner API URL'
    required: true
    default: 'https://api.ghostscanner.com'
  api_key:
    description: 'Ghost Scanner API Key'
    required: true
  scan_types:
    description: 'Types of scans to run (secrets,dependencies)'
    required: false
    default: 'secrets,dependencies'
  fail_on_critical:
    description: 'Fail the workflow if critical findings are detected'
    required: false
    default: 'false'
  comment_on_pr:
    description: 'Post scan results as PR comment'
    required: false
    default: 'true'
  include_ai_analysis:
    description: 'Include AI-powered risk analysis'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run Ghost Scanner
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/src/entrypoint.sh
        ${{ github.action_path }}/src/entrypoint.sh
      env:
        GHOST_SCANNER_API_URL: ${{ inputs.api_url }}
        INPUT_API_KEY: ${{ inputs.api_key }}
        INPUT_SCAN_TYPES: ${{ inputs.scan_types }}
        INPUT_FAIL_ON_HIGH_RISK: ${{ inputs.fail_on_critical }}
        INPUT_COMMENT_ON_PR: ${{ inputs.comment_on_pr }}
        INPUT_INCLUDE_AI_ANALYSIS: ${{ inputs.include_ai_analysis }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
